local o = vim.o
local opt = vim.opt
local g = vim.g

g.mapleader = " "
o.number = true
o.relativenumber = true
o.expandtab = true
o.smarttab = true
o.cindent = true
o.autoindent = true
o.tabstop = 4
o.shiftwidth = 0
o.softtabstop = -1
o.clipboard = 'unnamedplus'
o.smartcase = true
o.incsearch = true
o.hlsearch = false
o.swapfile = false
o.scrolloff = 3
o.numberwidth = 4
o.showmode = false
o.signcolumn = 'yes'
opt.mouse = "a"
